using Integracao.ControlID.PoC.Models.ControlIDApi;

namespace Integracao.ControlID.PoC.Services.ControlIDApi
{
    public class OfficialApiCatalogService
    {
        private static readonly List<OfficialApiEndpointDefinition> Endpoints =
        [
            new() { Id = "login", Category = "Sessão", Title = "Login", Method = "POST", Path = "/login.fcgi", BodyKind = "json", ContentType = "application/json", Summary = "Autentica no equipamento e retorna a sessão.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/session/create-session/", SamplePayload = "{\n  \"login\": \"admin\",\n  \"password\": \"admin\"\n}" },
            new() { Id = "logout", Category = "Sessão", Title = "Logout", Method = "POST", Path = "/logout.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Encerra a sessão ativa no equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/session/destroy-session/" },
            new() { Id = "session-is-valid", Category = "Sessão", Title = "Validar Sessão", Method = "POST", Path = "/session_is_valid.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Verifica se a sessão informada ainda é válida.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/session/check-session/" },
            new() { Id = "hash-password", Category = "Sessão", Title = "Gerar Hash de Senha", Method = "POST", Path = "/user_hash_password.fcgi", BodyKind = "json", ContentType = "application/json", Summary = "Gera hash e salt compatíveis com a API para senha de usuário.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/change-login-password/", SamplePayload = "{\n  \"password\": \"123456\"\n}" },

            new() { Id = "load-objects", Category = "Objetos", Title = "Carregar Objetos", Method = "POST", Path = "/load_objects.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Consulta users, groups, cards, qrcodes e logs.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/objects/load-objects/", SamplePayload = "{\n  \"object\": \"users\"\n}" },
            new() { Id = "create-objects", Category = "Objetos", Title = "Criar Objetos", Method = "POST", Path = "/create_objects.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Cria objetos na base local do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/objects/create-objects/", SamplePayload = "{\n  \"object\": \"users\",\n  \"values\": [\n    {\n      \"id\": 1,\n      \"name\": \"Novo Usuário\",\n      \"registration\": \"1001\"\n    }\n  ]\n}" },
            new() { Id = "modify-objects", Category = "Objetos", Title = "Modificar Objetos", Method = "POST", Path = "/modify_objects.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Atualiza objetos existentes por filtro.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/objects/modify-objects/", SamplePayload = "{\n  \"object\": \"users\",\n  \"where\": { \"users\": { \"id\": 1 } },\n  \"values\": {\n    \"name\": \"Usuário Atualizado\"\n  }\n}" },
            new() { Id = "create-or-modify-objects", Category = "Objetos", Title = "Criar ou Modificar Objetos", Method = "POST", Path = "/create_or_modify_objects.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Cria novos registros ou altera objetos existentes em uma única chamada.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/objects/create-or-modify-objects/", SamplePayload = "{\n  \"object\": \"users\",\n  \"values\": [\n    {\n      \"id\": 1,\n      \"registration\": \"1001\",\n      \"name\": \"Walter H. White\"\n    }\n  ]\n}", Notes = "A página oficial usa a grafia create-or-modify-objects no título, mas o exemplo publicado segue /create_or_modify_objects.fcgi." },
            new() { Id = "destroy-objects", Category = "Objetos", Title = "Excluir Objetos", Method = "POST", Path = "/destroy_objects.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Remove objetos do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/objects/destroy-objects/", SamplePayload = "{\n  \"object\": \"users\",\n  \"where\": { \"users\": { \"id\": 1 } }\n}" },
            new() { Id = "export-objects", Category = "Objetos", Title = "Exportar Objetos", Method = "POST", Path = "/export_objects.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Exporta relatórios e objetos do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/synchronization/", SamplePayload = "{\n  \"object\": \"users\"\n}", Notes = "O retorno pode ser um arquivo binário para download." },

            new() { Id = "get-configuration", Category = "Configurações", Title = "Obter Configuração", Method = "POST", Path = "/get_configuration.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Lê módulos como general, ntp, interlock, video_player e monitor.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/configurations/get-configurations/", SamplePayload = "{\n  \"general\": {},\n  \"ntp\": {}\n}" },
            new() { Id = "set-configuration", Category = "Configurações", Title = "Alterar Configuração", Method = "POST", Path = "/set_configuration.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Aplica alterações de configuração.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/configurations/set-configurations/", SamplePayload = "{\n  \"general\": {\n    \"show_logo\": \"1\"\n  }\n}" },
            new() { Id = "set-network-interlock", Category = "Configurações", Title = "Configurar Intertravamento em Rede", Method = "POST", Path = "/set_network_interlock.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Habilita o intertravamento em rede e define bypass por API/REX.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/configurations/network-interlocking/", SamplePayload = "{\n  \"interlock_enabled\": 1,\n  \"api_bypass_enabled\": 0,\n  \"rex_bypass_enabled\": 0\n}" },
            new() { Id = "connection-test", Category = "Configurações", Title = "Teste de Conexão", Method = "POST", Path = "/connection_test.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Executa um teste de conectividade do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/configurations/diagnostics-tools/", SamplePayload = "{\n  \"host\": \"8.8.8.8\",\n  \"port\": 53\n}" },
            new() { Id = "ping-test", Category = "Configurações", Title = "Ping", Method = "POST", Path = "/ping_test.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Executa ping a partir do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/configurations/diagnostics-tools/", SamplePayload = "{\n  \"host\": \"8.8.8.8\"\n}" },
            new() { Id = "nslookup-test", Category = "Configurações", Title = "NSLookup", Method = "POST", Path = "/nslookup_test.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Resolve nomes DNS usando a configuração de rede do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/configurations/diagnostics-tools/", SamplePayload = "{\n  \"host\": \"www.controlid.com.br\"\n}" },

            new() { Id = "remote-user-authorization", Category = "Ações", Title = "Autorização Remota", Method = "POST", Path = "/remote_user_authorization.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Autoriza ou nega acesso com feedback visual.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote_access_authorization/", SamplePayload = "{\n  \"event\": 7,\n  \"user_id\": 6,\n  \"user_name\": \"Ada Lovelace\",\n  \"user_image\": false,\n  \"portal_id\": 1,\n  \"actions\": [\n    { \"action\": \"door\", \"parameters\": \"door=1\" }\n  ]\n}" },
            new() { Id = "execute-actions", Category = "Ações", Title = "Executar Ações", Method = "POST", Path = "/execute_actions.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Aciona porta, catraca, coletor ou SecBox.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote-door-and-turnstile-opening/", SamplePayload = "{\n  \"actions\": [\n    { \"action\": \"door\", \"parameters\": \"door=1\" }\n  ]\n}" },
            new() { Id = "door-state", Category = "Ações", Title = "Estado da Porta", Method = "POST", Path = "/door_state.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Consulta o estado de portas e SecBox.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote-door-and-turnstile-opening/", SamplePayload = "{}" },
            new() { Id = "message-to-screen", Category = "Ações", Title = "Mensagem na Tela", Method = "POST", Path = "/message_to_screen.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Mostra ou limpa uma mensagem na tela.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/display_message_on_screen/", SamplePayload = "{\n  \"message\": \"Mensagem enviada pela PoC\",\n  \"timeout\": 3000\n}" },
            new() { Id = "buzzer-buzz", Category = "Ações", Title = "Acionar Buzzer", Method = "POST", Path = "/buzzer_buzz.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Aciona remotamente o buzzer.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote_buzzer_activation/", SamplePayload = "{\n  \"frequency\": 4000,\n  \"duty_cycle\": 50,\n  \"timeout\": 1000\n}" },
            new() { Id = "remote-enroll", Category = "Ações", Title = "Cadastro Remoto", Method = "POST", Path = "/remote_enroll.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Inicia cadastro remoto de face, biometria, cartão, PIN ou senha.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote-enrollment-facial-biometry-card/", SamplePayload = "{\n  \"type\": \"face\",\n  \"user_id\": 123,\n  \"save\": true,\n  \"sync\": true\n}" },
            new() { Id = "cancel-remote-enroll", Category = "Ações", Title = "Cancelar Cadastro Remoto", Method = "POST", Path = "/cancel_remote_enroll.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Interrompe um fluxo de cadastro remoto.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote-enrollment-facial-biometry-card/" },
            new() { Id = "get-catra-info", Category = "Catraca", Title = "Informações de Giro da Catraca", Method = "GET", Path = "/get_catra_info.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Obtém totais de giro da catraca, incluindo entrada, saída, esquerda e direita.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-pt/reconhecimento-facial/informacoes-catraca/" },

            new() { Id = "user-get-image", Category = "Fotos e Logotipo", Title = "Obter Foto do Usuário", Method = "GET", Path = "/user_get_image.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Baixa a foto do usuário cadastrada no equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/photos-and-logo/manage-user-pictures/", Notes = "Informe user_id em 'query adicional'. Exemplo: user_id=123" },
            new() { Id = "user-list-images", Category = "Fotos e Logotipo", Title = "Listar Fotos de Usuários", Method = "GET", Path = "/user_list_images.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Lista usuários que possuem imagem cadastrada.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/photos-and-logo/manage-user-pictures/" },
            new() { Id = "user-get-image-list", Category = "Fotos e Logotipo", Title = "Obter Lista de Fotos", Method = "POST", Path = "/user_get_image_list.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Retorna fotos em base64 para uma lista de usuários.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/facial-recognition/facial-enroll/", SamplePayload = "{\n  \"user_ids\": [1, 2, 3]\n}" },
            new() { Id = "user-set-image", Category = "Fotos e Logotipo", Title = "Enviar Foto do Usuário", Method = "POST", Path = "/user_set_image.fcgi", BodyKind = "multipart", ContentType = "multipart/form-data", RequiresSession = true, Summary = "Envia foto de usuário ao equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/photos-and-logo/manage-user-pictures/", Notes = "Use JSON multipart: { \"fields\": { \"user_id\": \"123\" }, \"files\": [ { \"name\": \"image\", \"fileName\": \"foto.jpg\", \"contentType\": \"image/jpeg\", \"base64Content\": \"...\" } ] }" },
            new() { Id = "user-set-image-list", Category = "Fotos e Logotipo", Title = "Enviar Lista de Fotos", Method = "POST", Path = "/user_set_image_list.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Registra fotos faciais em lote via JSON/base64.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/facial-recognition/facial-enroll/", SamplePayload = "{\n  \"match\": false,\n  \"user_images\": [\n    {\n      \"user_id\": 1,\n      \"timestamp\": 1713000000,\n      \"image\": \"BASE64\"\n    }\n  ]\n}" },
            new() { Id = "user-test-image", Category = "Fotos e Logotipo", Title = "Testar Foto Facial", Method = "POST", Path = "/user_test_image.fcgi", BodyKind = "binary", ContentType = "application/octet-stream", RequiresSession = true, Summary = "Valida se uma imagem facial atenderia aos critérios de cadastro.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/facial-recognition/facial-enroll/", Notes = "Envie o corpo como base64 puro do JPG ou PNG." },
            new() { Id = "user-destroy-image", Category = "Fotos e Logotipo", Title = "Excluir Foto do Usuário", Method = "POST", Path = "/user_destroy_image.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Remove a foto de um usuário no equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/photos-and-logo/manage-user-pictures/", SamplePayload = "{\n  \"user_id\": 123\n}" },
            new() { Id = "logo-get", Category = "Fotos e Logotipo", Title = "Obter Logo", Method = "POST", Path = "/logo.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Obtém o logo armazenado no slot indicado.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/photos-and-logo/manage-logo/", Notes = "Informe id do slot em 'query adicional'. Exemplo: id=1" },
            new() { Id = "logo-change", Category = "Fotos e Logotipo", Title = "Alterar Logo", Method = "POST", Path = "/logo_change.fcgi", BodyKind = "binary", ContentType = "application/octet-stream", RequiresSession = true, Summary = "Substitui o logo do slot informado com PNG em binário.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/photos-and-logo/manage-logo/", Notes = "Envie o corpo como base64 puro do PNG. Use 'query adicional' para passar id=1..8." },
            new() { Id = "logo-destroy", Category = "Fotos e Logotipo", Title = "Excluir Logo", Method = "POST", Path = "/logo_destroy.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Apaga o logo do slot informado.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/photos-and-logo/manage-logo/", Notes = "Use 'query adicional' para passar id=1..8." },
            new() { Id = "send-video", Category = "Fotos e Logotipo", Title = "Enviar Vídeo de Propaganda", Method = "POST", Path = "/send_video.fcgi", BodyKind = "binary", ContentType = "application/octet-stream", RequiresSession = true, Summary = "Envia fragmentos do vídeo MP4 para modo propaganda.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/photos-and-logo/manage-ad-mode/", Notes = "Envie o corpo como base64 do bloco binário e use 'query adicional' com current=1&total=2." },
            new() { Id = "set-custom-video", Category = "Fotos e Logotipo", Title = "Habilitar Vídeo Personalizado", Method = "POST", Path = "/set_custom_video.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Habilita ou desabilita o modo propaganda.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/photos-and-logo/manage-ad-mode/", SamplePayload = "{\n  \"custom_video_enabled\": \"1\"\n}" },
            new() { Id = "remove-custom-video", Category = "Fotos e Logotipo", Title = "Remover Vídeo Personalizado", Method = "POST", Path = "/remove_custom_video.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Remove o vídeo carregado para modo propaganda.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/photos-and-logo/manage-ad-mode/" },
            new() { Id = "save-screenshot", Category = "Fotos e Logotipo", Title = "Capturar Imagem da Câmera", Method = "POST", Path = "/save_screenshot.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Captura uma imagem RGB ou IR da câmera do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/facial-recognition/camera-capture/", SamplePayload = "{\n  \"frame_type\": \"camera\",\n  \"camera\": \"rgb\"\n}" },

            new() { Id = "system-information", Category = "Sistema", Title = "Informações do Sistema", Method = "POST", Path = "/system_information.fcgi", BodyKind = "none", Summary = "Consulta versão, serial, modelo e outras informações do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/system-information/" },
            new() { Id = "change-login", Category = "Sistema", Title = "Alterar Login do Equipamento", Method = "POST", Path = "/change_login.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Altera o usuário e/ou senha utilizados para login no equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/session-management/change-username-and-password-login/", SamplePayload = "{\n  \"login\": \"admin\",\n  \"password\": \"novaSenha123\"\n}" },
            new() { Id = "set-system-time", Category = "Sistema", Title = "Ajustar Data e Hora", Method = "POST", Path = "/set_system_time.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Define data e hora do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/change-date-and-time/", SamplePayload = "{\n  \"day\": 13,\n  \"month\": 4,\n  \"year\": 2026,\n  \"hour\": 10,\n  \"minute\": 30,\n  \"second\": 0\n}" },
            new() { Id = "reset-to-factory", Category = "Sistema", Title = "Reset de Fábrica", Method = "POST", Path = "/reset_to_factory_default.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Restaura o equipamento ao padrão de fábrica.", DocumentationUrl = "https://www.controlid.com.br/suporte/api_idaccess_V2.6.8.html", SamplePayload = "{\n  \"keep_network_info\": true\n}" },
            new() { Id = "reboot", Category = "Sistema", Title = "Reiniciar Equipamento", Method = "POST", Path = "/reboot.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Reinicia o equipamento.", DocumentationUrl = "https://www.controlid.com.br/suporte/api_idaccess_V2.6.8.html" },
            new() { Id = "reboot-recovery", Category = "Sistema", Title = "Reiniciar em Modo Update", Method = "POST", Path = "/reboot_recovery.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Reinicia em modo de atualização.", DocumentationUrl = "https://www.controlid.com.br/suporte/api_idaccess_V2.6.8.html" },
            new() { Id = "delete-admins", Category = "Sistema", Title = "Remover Administradores", Method = "POST", Path = "/delete_admins.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Remove todos os administradores do equipamento.", DocumentationUrl = "https://www.controlid.com.br/suporte/api_idaccess_V2.6.8.html" },
            new() { Id = "set-system-network", Category = "Sistema", Title = "Configurar Rede", Method = "POST", Path = "/set_system_network.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Altera parâmetros de rede do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/network-settings/", SamplePayload = "{\n  \"ip\": \"192.168.0.10\",\n  \"mask\": \"255.255.255.0\",\n  \"gateway\": \"192.168.0.1\"\n}" },

            new() { Id = "ssl-certificate-change", Category = "Sistema", Title = "Alterar Certificado SSL", Method = "POST", Path = "/ssl_certificate_change.fcgi", BodyKind = "binary", ContentType = "application/octet-stream", RequiresSession = true, Summary = "Envia um certificado PEM para o servidor web do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/network-settings/", Notes = "Envie o corpo como base64 puro do arquivo PEM." },
            new() { Id = "set-vpn-information", Category = "Sistema", Title = "Configurar OpenVPN", Method = "POST", Path = "/set_vpn_information.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Altera as configurações de uso do OpenVPN no equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/network-settings/", SamplePayload = "{\n  \"enabled\": true,\n  \"login_enabled\": true,\n  \"login\": \"Admin\",\n  \"password\": \"Admin\"\n}" },
            new() { Id = "get-vpn-information", Category = "Sistema", Title = "Ler Configuração OpenVPN", Method = "GET", Path = "/get_vpn_information.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Consulta a configuração atual do OpenVPN.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/network-settings/" },
            new() { Id = "get-vpn-status", Category = "Sistema", Title = "Ler Status OpenVPN", Method = "GET", Path = "/get_vpn_status.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Consulta o status atual da conexão OpenVPN.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/network-settings/" },
            new() { Id = "has-vpn-file", Category = "Sistema", Title = "Verificar Arquivo OpenVPN", Method = "GET", Path = "/has_vpn_file.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Informa se já existe um arquivo de configuração OpenVPN no equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/network-settings/" },
            new() { Id = "set-vpn-file", Category = "Sistema", Title = "Enviar Arquivo OpenVPN", Method = "POST", Path = "/set_vpn_file.fcgi", BodyKind = "binary", ContentType = "application/octet-stream", RequiresSession = true, Summary = "Envia o arquivo .conf ou .zip usado pelo OpenVPN.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/network-settings/", Notes = "Envie o corpo como base64 puro e passe file_type=config ou file_type=zip na query." },
            new() { Id = "get-vpn-file", Category = "Sistema", Title = "Baixar Arquivo Exemplo OpenVPN", Method = "GET", Path = "/get_vpn_file.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Baixa um arquivo exemplo de parametrização para OpenVPN.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/network-settings/" },
            new() { Id = "gpio-state", Category = "Hardware", Title = "Ler Estado de GPIO", Method = "POST", Path = "/gpio_state.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Lê o estado de um GPIO específico do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/hardware/read-gpio-status/", SamplePayload = "{\n  \"gpio\": 1\n}" },
            new() { Id = "reread-leds", Category = "Hardware", Title = "Recarregar Configuração de LEDs", Method = "POST", Path = "/reread_leds_settings.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Reaplica a configuração de LEDs sem reiniciar o equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/hardware/reread-led-configuration/" },
            new() { Id = "remote-led-control", Category = "Hardware", Title = "Controlar LED Remotamente", Method = "POST", Path = "/remote_led_control.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Controla os LEDs RGB da iDBlock Next via evento remoto.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-pt/particularidade-dos-produtos/idblock-next/", SamplePayload = "{\n  \"sec_box\": {\n    \"color\": \"4278255360\",\n    \"event\": 4\n  }\n}" },
            new() { Id = "validate-biometry", Category = "Hardware", Title = "Validar Biometria", Method = "POST", Path = "/is_valid_biometry.fcgi", BodyKind = "binary", ContentType = "application/octet-stream", RequiresSession = true, Summary = "Valida uma biometria enviada em formato binário/base64.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/system/verify_biometry/", Notes = "Envie o corpo como base64 puro do template ou imagem exigida pelo endpoint." },

            new() { Id = "cb-new-user-identified", Category = "Callbacks Online", Title = "Evento de Usuário Identificado", Direction = "server-callback", Method = "POST", Path = "/new_user_identified.fcgi", BodyKind = "form", Invokable = false, Summary = "Recebe usuário identificado localmente em modo Pro.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/operating-modes/online-identification-events/" },
            new() { Id = "cb-new-card", Category = "Callbacks Online", Title = "Evento de Cartão", Direction = "server-callback", Method = "POST", Path = "/new_card.fcgi", BodyKind = "form", Invokable = false, Summary = "Recebe tentativa de identificação por cartão em modo online.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/operating-modes/online-identification-events/" },
            new() { Id = "cb-new-biometric-image", Category = "Callbacks Online", Title = "Evento de Imagem Biométrica", Direction = "server-callback", Method = "POST", Path = "/new_biometric_image.fcgi", BodyKind = "binary", Invokable = false, Summary = "Recebe tentativa de identificação biométrica por imagem.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/operating-modes/online-identification-events/" },
            new() { Id = "cb-device-alive", Category = "Callbacks Online", Title = "Heartbeat do Dispositivo", Direction = "server-callback", Method = "POST", Path = "/device_is_alive.fcgi", BodyKind = "json", Invokable = false, Summary = "Recebe heartbeat/contingência do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/operating-modes/online-identification-events/" },
            new() { Id = "cb-card-create", Category = "Callbacks Online", Title = "Retorno de Cadastro Remoto de Cartão", Direction = "server-callback", Method = "POST", Path = "/card_create.fcgi", BodyKind = "json", Invokable = false, Summary = "Recebe retorno do cadastro remoto de cartão.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote-enrollment-facial-biometry-card/" },
            new() { Id = "cb-user-image", Category = "Monitor", Title = "Notificação de Imagem do Usuário", Direction = "server-callback", Method = "POST", Path = "/api/notifications/user_image", BodyKind = "json", Invokable = false, Summary = "Recebe imagem do usuário pelo monitor.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/monitor/introduction-to-monitor/" },
            new() { Id = "cb-monitor-template", Category = "Monitor", Title = "Notificação de Template", Direction = "server-callback", Method = "POST", Path = "/api/notifications/template", BodyKind = "json", Invokable = false, Summary = "Recebe template remoto pelo monitor.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/monitor/introduction-to-monitor/" },
            new() { Id = "cb-monitor-card", Category = "Monitor", Title = "Notificação de Cartão", Direction = "server-callback", Method = "POST", Path = "/api/notifications/card", BodyKind = "json", Invokable = false, Summary = "Recebe cartão remoto pelo monitor.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/monitor/introduction-to-monitor/" },
            new() { Id = "cb-monitor-operation-mode", Category = "Monitor", Title = "Notificação de Modo de Operação", Direction = "server-callback", Method = "POST", Path = "/api/notifications/operation_mode", BodyKind = "json", Invokable = false, Summary = "Recebe mudanças de modo de operação do equipamento.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/monitor/introduction-to-monitor/" }
        ];

        private static readonly List<OfficialApiEndpointDefinition> AdditionalEndpoints =
        [
            new() { Id = "cb-new-qrcode", Category = "Callbacks Online", Title = "Evento de QR Code", Direction = "server-callback", Method = "POST", Path = "/new_qrcode.fcgi", BodyKind = "form", Invokable = false, Summary = "Recebe tentativa de identificacao por QR Code em modo online.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-pt/modos-de-operacao/eventos-de-identificacao-online/" },
            new() { Id = "cb-new-biometric-template", Category = "Callbacks Online", Title = "Evento de Template Biometrico", Direction = "server-callback", Method = "POST", Path = "/new_biometric_template.fcgi", BodyKind = "binary", Invokable = false, Summary = "Recebe tentativa de identificacao biometrica por template.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/operating-modes/online-identification-events/" },
            new() { Id = "cb-new-uhf-tag", Category = "Callbacks Online", Title = "Evento de Tag UHF", Direction = "server-callback", Method = "POST", Path = "/new_uhf_tag.fcgi", BodyKind = "form", Invokable = false, Summary = "Recebe tentativa de identificacao por tag UHF em modo online.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/operating-modes/online-identification-events/" },
            new() { Id = "cb-new-user-id-password", Category = "Callbacks Online", Title = "Evento de ID e Senha", Direction = "server-callback", Method = "POST", Path = "/new_user_id_and_password.fcgi", BodyKind = "form", Invokable = false, Summary = "Recebe tentativa de identificacao por ID e senha.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/operating-modes/online-identification-events/" },
            new() { Id = "cb-template-create", Category = "Callbacks Online", Title = "Retorno de Template Remoto", Direction = "server-callback", Method = "POST", Path = "/template_create.fcgi", BodyKind = "json", Invokable = false, Summary = "Recebe templates biometricos do cadastro remoto.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote-enrollment-facial-biometry-card/" },
            new() { Id = "cb-face-create", Category = "Callbacks Online", Title = "Retorno de Cadastro Remoto de Face", Direction = "server-callback", Method = "POST", Path = "/face_create.fcgi", BodyKind = "json", Invokable = false, Summary = "Recebe imagem facial gerada no cadastro remoto.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote-enrollment-facial-biometry-card/" },
            new() { Id = "cb-pin-create", Category = "Callbacks Online", Title = "Retorno de Cadastro Remoto de PIN", Direction = "server-callback", Method = "POST", Path = "/pin_create.fcgi", BodyKind = "json", Invokable = false, Summary = "Recebe PIN cadastrado remotamente.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote-enrollment-facial-biometry-card/" },
            new() { Id = "cb-password-create", Category = "Callbacks Online", Title = "Retorno de Cadastro Remoto de Senha", Direction = "server-callback", Method = "POST", Path = "/password_create.fcgi", BodyKind = "json", Invokable = false, Summary = "Recebe senha cadastrada remotamente.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/actions/remote-enrollment-facial-biometry-card/" },
            new() { Id = "push-poll", Category = "Push", Title = "Fila Push do Servidor", Direction = "server-callback", Method = "GET", Path = "/push", BodyKind = "none", Invokable = false, Summary = "Endpoint servido pela PoC para o equipamento buscar comandos pendentes.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/push/introduction-to-push/" },
            new() { Id = "push-result", Category = "Push", Title = "Resultado Push", Direction = "server-callback", Method = "POST", Path = "/result", BodyKind = "json", Invokable = false, Summary = "Endpoint servido pela PoC para o equipamento devolver o resultado de um comando push.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/push/introduction-to-push/" },
            new() { Id = "cb-monitor-pin", Category = "Monitor", Title = "Notificacao de PIN", Direction = "server-callback", Method = "POST", Path = "/api/notifications/pin", BodyKind = "json", Invokable = false, Summary = "Recebe PIN de cadastro remoto via monitor.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-pt/monitor/introducao-ao-monitor/" },
            new() { Id = "cb-monitor-password", Category = "Monitor", Title = "Notificacao de Senha", Direction = "server-callback", Method = "POST", Path = "/api/notifications/password", BodyKind = "json", Invokable = false, Summary = "Recebe senha de cadastro remoto via monitor.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-pt/monitor/introducao-ao-monitor/" },
            new() { Id = "cb-monitor-catra-event", Category = "Monitor", Title = "Notificacao de Catraca", Direction = "server-callback", Method = "POST", Path = "/api/notifications/catra_event", BodyKind = "json", Invokable = false, Summary = "Recebe eventos de confirmacao de giro da catraca.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-pt/monitor/introducao-ao-monitor/" },
            new() { Id = "cb-monitor-usb-drive", Category = "Monitor", Title = "Notificacao de USB Drive", Direction = "server-callback", Method = "POST", Path = "/api/notifications/usb_drive", BodyKind = "json", Invokable = false, Summary = "Recebe eventos de exportacao para USB.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/monitor/introduction-to-monitor/" },
            new() { Id = "report-generate", Category = "Relatorios", Title = "Gerar Relatorio", Method = "POST", Path = "/report_generate.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Gera relatorios customizados com colunas, filtros e ordenacao.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/objects/export-report/", SamplePayload = "{\n  \"object\": \"users\",\n  \"order\": [\"ascending\", \"name\"],\n  \"where\": {\n    \"users\": {},\n    \"groups\": {},\n    \"time_zones\": {}\n  },\n  \"delimiter\": \";\",\n  \"line_break\": \"\\r\\n\",\n  \"header\": \"Name (User);Id (User)\",\n  \"file_name\": \"\",\n  \"join\": \"LEFT\",\n  \"columns\": [\n    {\n      \"type\": \"object_field\",\n      \"object\": \"users\",\n      \"field\": \"name\"\n    },\n    {\n      \"type\": \"object_field\",\n      \"object\": \"users\",\n      \"field\": \"id\"\n    }\n  ]\n}", Notes = "O retorno normalmente e um arquivo texto/binario pronto para download." },
            new() { Id = "export-afd", Category = "Relatorios", Title = "Exportar AFD", Method = "POST", Path = "/export_afd.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Exporta relatorio AFD com suporte aos formatos 595 e 671.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/objects/export-report/", SamplePayload = "{\n  \"initial_nsr\": 1\n}", Notes = "Use 'query adicional' com mode=671 para o formato da Portaria 671." },
            new() { Id = "export-audit-logs", Category = "Relatorios", Title = "Exportar Logs de Auditoria", Method = "POST", Path = "/export_audit_logs.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Exporta os ultimos logs de auditoria por categoria.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/objects/export-report/", SamplePayload = "{\n  \"config\": 1,\n  \"api\": 1,\n  \"usb\": 1,\n  \"network\": 1,\n  \"time\": 1,\n  \"online\": 1,\n  \"menu\": 1\n}", Notes = "O retorno e um documento texto gerado pelo equipamento." },
            new() { Id = "change-idcloud-code", Category = "Push", Title = "Regenerar Codigo do iDCloud", Method = "GET", Path = "/change_idcloud_code.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Gera um novo codigo de verificacao para integracao com o iDCloud.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/push-mode/idcloud/" },
            new() { Id = "alarm-status", Category = "Alarme", Title = "Status do Alarme", Method = "POST", Path = "/alarm_status.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Consulta ou interrompe o estado atual do alarme do dispositivo.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/alarm/introduction-to-alarm/", SamplePayload = "{\n  \"stop\": false\n}" },
            new() { Id = "upgrade-idface-pro", Category = "Particularidades", Title = "Upgrade iDFace Pro", Method = "POST", Path = "/upgrade_ten_thousand_face_templates.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Atualiza o iDFace Lite para o modo Pro mediante senha/licenca da Control iD.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/update-idface/", SamplePayload = "{\n  \"password\": \"ABCDE12345\"\n}" },
            new() { Id = "upgrade-idflex-enterprise", Category = "Particularidades", Title = "Upgrade iDFlex/iDAccess Nano Enterprise", Method = "POST", Path = "/idflex_upgrade_enterprise.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Habilita o modo Enterprise em iDFlex ou iDAccess Nano mediante senha/licenca.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/update-idflex-idaccess-nano/", SamplePayload = "{\n  \"password\": \"ABCDE12345\"\n}" },
            new() { Id = "set-pjsip-audio-message", Category = "Intercom SIP", Title = "Enviar Toque Personalizado do SIP", Method = "POST", Path = "/set_pjsip_audio_message.fcgi", BodyKind = "binary", ContentType = "application/octet-stream", RequiresSession = true, Summary = "Envia o arquivo WAV do toque personalizado do intercom SIP em blocos.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/sip-intercom-idface/", Notes = "Envie o corpo como base64 puro do WAV e passe current=1&total=1 na query." },
            new() { Id = "get-pjsip-audio-message", Category = "Intercom SIP", Title = "Baixar Toque Personalizado do SIP", Method = "POST", Path = "/get_pjsip_audio_message.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Baixa o arquivo WAV de toque personalizado do intercom SIP.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/sip-intercom-idface/" },
            new() { Id = "has-pjsip-audio-message", Category = "Intercom SIP", Title = "Verificar Toque Personalizado do SIP", Method = "POST", Path = "/has_pjsip_audio_message.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Informa se o dispositivo possui um toque personalizado de intercom.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/sip-intercom-idface/" },
            new() { Id = "make-sip-call", Category = "Intercom SIP", Title = "Iniciar Chamada SIP", Method = "POST", Path = "/make_sip_call.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Inicia uma chamada SIP para o ramal informado.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/sip-intercom-idface/", SamplePayload = "{\n  \"target\": \"503\"\n}" },
            new() { Id = "finalize-sip-call", Category = "Intercom SIP", Title = "Encerrar Chamada SIP", Method = "POST", Path = "/finalize_sip_call.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Encerra a chamada SIP atual.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/sip-intercom-idface/" },
            new() { Id = "get-sip-status", Category = "Intercom SIP", Title = "Consultar Status do SIP", Method = "POST", Path = "/get_sip_status.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Consulta o status atual do registro/chamada SIP.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/sip-intercom-idface/" },
            new() { Id = "set-audio-access-message", Category = "Audio iDFace", Title = "Enviar Audio de Evento de Acesso", Method = "POST", Path = "/set_audio_access_message.fcgi", BodyKind = "binary", ContentType = "application/octet-stream", RequiresSession = true, Summary = "Envia o audio customizado de um evento de identificacao do iDFace em blocos.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/access-audio-messages-idface/", Notes = "Envie o corpo como base64 puro do WAV e passe event=authorized&current=1&total=1 na query." },
            new() { Id = "get-audio-access-message", Category = "Audio iDFace", Title = "Baixar Audio de Evento de Acesso", Method = "POST", Path = "/get_audio_access_message.fcgi", BodyKind = "json", RequiresSession = true, Summary = "Baixa o audio customizado configurado para um evento de identificacao.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/access-audio-messages-idface/", SamplePayload = "{\n  \"event\": \"authorized\"\n}" },
            new() { Id = "has-audio-access-messages", Category = "Audio iDFace", Title = "Verificar Audios de Acesso", Method = "POST", Path = "/has_audio_access_messages.fcgi", BodyKind = "none", RequiresSession = true, Summary = "Consulta quais eventos de identificacao possuem audio customizado no iDFace.", DocumentationUrl = "https://www.controlid.com.br/docs/access-api-en/particularities-of-the-products/access-audio-messages-idface/" }
        ];

        public List<OfficialApiEndpointDefinition> GetAll()
        {
            return Endpoints.Concat(AdditionalEndpoints).OrderBy(endpoint => endpoint.Category).ThenBy(endpoint => endpoint.Title).ToList();
        }

        public List<string> GetCategories()
        {
            return Endpoints.Concat(AdditionalEndpoints).Select(endpoint => endpoint.Category).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(category => category).ToList();
        }

        public OfficialApiEndpointDefinition? GetById(string id)
        {
            return Endpoints.Concat(AdditionalEndpoints).FirstOrDefault(endpoint => endpoint.Id.Equals(id, StringComparison.OrdinalIgnoreCase));
        }
    }
}
