// <auto-generated />
using Integracao.ControlID.PoC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Integracao.ControlID.PoC.Data.Migrations
{
    [DbContext(typeof(IntegracaoControlIDContext))]
    [Migration("20260430233000_AddLocalUserRoles")]
    partial class AddLocalUserRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");
#pragma warning restore 612, 618
        }
    }
}
